"""Shared PyInstaller helpers used by both ``.spec`` files.

Keeping the exclude/hidden-import lists in one place guarantees that the main
application and the administrator utility are frozen with identical Qt
plugin sets, which keeps both binaries small and their behaviour consistent.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

#: Qt modules that PySide6 pulls in by default but Agent3 never imports.
EXCLUDED_MODULES = [
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebEngineQuick",
    "PySide6.QtWebChannel",
    "PySide6.QtWebSockets",
    "PySide6.QtQuick",
    "PySide6.QtQuick3D",
    "PySide6.QtQml",
    "PySide6.QtQuickWidgets",
    "PySide6.Qt3DCore",
    "PySide6.Qt3DRender",
    "PySide6.QtCharts",
    "PySide6.QtDataVisualization",
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    "PySide6.QtPdf",
    "PySide6.QtPdfWidgets",
    "PySide6.QtOpenGL",
    "PySide6.QtOpenGLWidgets",
    "PySide6.QtPositioning",
    "PySide6.QtRemoteObjects",
    "PySide6.QtSensors",
    "PySide6.QtSerialPort",
    "PySide6.QtSpatialAudio",
    "PySide6.QtTest",
    "PySide6.QtTextToSpeech",
    "PySide6.QtDesigner",
    "PySide6.QtUiTools",
    "PySide6.QtHelp",
    "PySide6.QtBluetooth",
    "PySide6.QtNfc",
    "PySide6.QtScxml",
    "PySide6.QtStateMachine",
    # NOTE: never exclude ``shiboken6`` or ``shiboken6.Shiboken`` here - it is
    # the C++ binding layer that ``import PySide6`` loads first. Excluding it
    # produces a binary that dies with
    # "ModuleNotFoundError: No module named 'shiboken6.Shiboken'".
    # Likewise, stdlib modules such as ``unittest`` stay in: several third
    # party packages import them lazily and the size saving is negligible.
    # Scientific / dev-only packages that must never land in the binary.
    "tkinter",
    "numpy",
    "pandas",
    "matplotlib",
    "scipy",
    "PIL",
    "pytest",
    "setuptools",
    "pip",
]

#: Modules imported indirectly (plugin style) that PyInstaller cannot see.
HIDDEN_IMPORTS = [
    "shiboken6",
    "shiboken6.Shiboken",
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "PySide6.QtSvg",
    "cryptography.hazmat.primitives.ciphers.aead",
    "cryptography.hazmat.primitives.kdf.pbkdf2",
    "cryptography.hazmat.backends.openssl",
    "sqlite3",
    "encodings.idna",
    # Standard-library parsers used by the automatic syntax checker. They are
    # imported lazily inside agent3.workspace.syntax_check, which PyInstaller's
    # static analysis would otherwise miss.
    "tomllib",
    "configparser",
    "xml.etree.ElementTree",
]


def project_root(spec_path: str) -> Path:
    """Return the repository root.

    PyInstaller injects ``SPECPATH`` as the *directory* containing the spec
    file, but the helpers are also handy with a full spec file path, so both
    forms are accepted.
    """
    path = Path(spec_path).resolve()
    packaging_dir = path if path.is_dir() else path.parent
    return packaging_dir.parent


def source_root(spec_path: str) -> Path:
    return project_root(spec_path) / "src"


def resource_datas(spec_path: str) -> list[tuple[str, str]]:
    """Bundle the icon/resource folder next to the frozen modules."""
    resources = source_root(spec_path) / "agent3" / "resources"
    if not resources.is_dir():
        return []
    return [(str(resources), "resources")]


def icon_path(spec_path: str) -> str | None:
    """Return the platform appropriate application icon, if present."""
    resources = source_root(spec_path) / "agent3" / "resources"
    candidate = resources / ("agent3.ico" if sys.platform.startswith("win") else "agent3.png")
    return str(candidate) if candidate.exists() else None


def version_file(spec_path: str) -> str | None:
    """Windows VERSIONINFO resource (generated by ``make_version_file.py``)."""
    candidate = project_root(spec_path) / "packaging" / "version_info.txt"
    if sys.platform.startswith("win") and candidate.exists():
        return str(candidate)
    return None


def console_mode() -> bool:
    """Show a console window only when AGENT3_BUILD_CONSOLE=1 (debug builds)."""
    return os.environ.get("AGENT3_BUILD_CONSOLE", "0") == "1"
